### ISSUE TITLE
wildstacker compatiblity issue, dead mob add >1 chunkheat and does not reduce 

### ISSUE THREAD

**Issue by hkkongou** [Ghost-chu/ChunkHeat#4]
with wildstacker installed, player found out that if they kill mob using any weapon, chunkheat will increase by 3 atleast, and the number does not drop unless the reset-time from config.yml is reached 
WildStacker-2023.2-b5
ChunkHeat-1.1.1
purpur-1.20.1-2006
https://youtu.be/Vw5Uy-zW5Mk

**Comment by Ghost-chu** [comment]
In the default configuration, zombie piglin will add 3 heats to their chunks, it looks work as intended.

https://github.com/Ghost-chu/ChunkHeat/blob/992647c226fce53edca45f1331eb2685eba5ce6d/src/main/resources/config.yml#L48C3-L48C19

**Comment by Ghost-chu** [comment]
鉴于您似乎可以阅读中文，我将使用中文回复此 Issue。

ChunkHeat 的工作机制是当一个生物死亡时，ChunkHeat 会读取配置文件中配置的 “生物权重”，并按权重值为区块 “升温”。升温的幅度取决于您在配置文件中指定的权重值。  

对于僵尸猪灵来说，它的默认值被设置为 `3`，这符合预期效果（也就是您在视频中演示的那样）。

对于您所说的热力值不会下降的问题，设计即是如此。ChunkHeat 提供两种为区块热度 “降温” 的计时方式：

- 经过一段固定时间后区块热度即会被重置
- 只有当区块不再活动，区块热度才会被重置

第一种是为了阻止玩家建造大规模刷怪设施，只允许这些设施占用一段时间的服务器资源，设施越大，则会更快被限制。它的工作原理更像是 “时间分片”。
第二种是为了完全阻止玩家通过刷怪设施获得好处，一旦达到上限，除非玩家离开过热区块，否则该区块不再会刷新任何怪物。

不管哪一种，它都不会“逐步下降”。

**Comment by Ghost-chu** [comment]
您可能会注意到与此同时，如果区块热度达到上限，则不会产生任何掉落物和经验，这也是预期行为且暂时无法被关闭，这与 #3 有关。

然而，这正是 ChunkHeat 的设计初衷——通过区块热度机制没收生物农场的产出。从而使玩家失去建造大型刷怪设施的想法，阻止玩家使用该类设备过度消耗服务器资源。
